"""
Problem: Find the Difference

You are given two strings s and t.

String t is generated by randomly shuffling string s
and adding one extra character.

Return the extra character.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e
"""


def find_the_difference(s, t):

    count = {}

    for ch in s:
        count[ch] = count.get(ch, 0) + 1

    for ch in t:

        if ch not in count:
            return ch

        count[ch] -= 1

        if count[ch] < 0:
            return ch

    return ""


# Test Cases
print(find_the_difference("abcd", "abcde"))
print(find_the_difference("", "y"))
print(find_the_difference("ae", "aea"))